trigger:
- dev
variables:
  BuildParameters.ArtifactName: drop
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)/infra/gcp'
    inputs:
      SourceFolder: infra
      TargetFolder: $(build.artifactstagingdirectory)/infra/gcp
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)/infra/gcp'
    inputs:
      SourceFolder: src
      TargetFolder: $(build.artifactstagingdirectory)/src
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: $(BuildParameters.ArtifactName)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
...
